import "./globals.css";
// toastify
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Slide } from "react-toastify";

import TanstackProvider from "@/providers/TanstackProvider";

export const metadata = {
  title: "MyTube",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* react toastify */}
        <ToastContainer
          position="bottom-center"
          autoClose={2500}
          transition={Slide}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
